from fastapi import APIRouter, Depends
from pydantic import BaseModel, Field
from app.dependencies import verify_api_key
from app.agents.basic.dynamic_prompt_agent import update_system_prompt, execute_dynamic_prompt_agent
from app.agents.basic.lifecycle_agent import initialize_agent, execute_agent, terminate_agent

router = APIRouter(tags=["Basic Agents"])

# ------------------------------
# Lifecycle Agent Endpoints
# ------------------------------

class ExecuteLifecycleRequest(BaseModel):
    input: str = Field(..., description="Input for the lifecycle agent execution.")

class LifecycleResponse(BaseModel):
    result: str = Field(..., description="Result of lifecycle agent execution.")

@router.post(
    "/lifecycle/initialize",
    dependencies=[Depends(verify_api_key)],
    summary="Initialize the lifecycle agent",
    description="""
    Initialize the lifecycle agent and return a confirmation message.
    The agent becomes active and ready to process input.
    """
)
async def lifecycle_initialize():
    message = initialize_agent()
    return {"message": message}

@router.post(
    "/lifecycle/execute",
    response_model=LifecycleResponse,
    dependencies=[Depends(verify_api_key)],
    summary="Execute the lifecycle agent",
    description="""
    Execute the lifecycle agent using the provided input.
    This endpoint calls the agent's execute function, ensuring that the agent
    is active and ready. It returns the processing result.
    """
)
async def lifecycle_execute(request: ExecuteLifecycleRequest):
    result = execute_agent({"input": request.input})
    return LifecycleResponse(result=result)

@router.post(
    "/lifecycle/terminate",
    dependencies=[Depends(verify_api_key)],
    summary="Terminate the lifecycle agent",
    description="""
    Terminate the lifecycle agent and return a termination confirmation message.
    This action deactivates the agent, preventing further execution until re-initialized.
    """
)
async def lifecycle_terminate():
    message = terminate_agent()
    return {"message": message}

# ------------------------------
# Dynamic Prompt Endpoints
# ------------------------------

class PromptUpdateRequest(BaseModel):
    new_prompt: str = Field(
        ...,
        description="The new prompt text to update the agent's system prompt. This value replaces the current prompt."
    )

class PromptUpdateResponse(BaseModel):
    prompt: str = Field(
        ...,
        description="The updated system prompt after processing the request."
    )

class DynamicPromptExecuteRequest(BaseModel):
    input: str = Field(
        ...,
        description="The input data for the dynamic prompt agent to process."
    )

class DynamicPromptExecuteResponse(BaseModel):
    response: str = Field(
        ...,
        description="The response generated by the dynamic prompt agent using the current system prompt and the provided input."
    )

@router.post(
    "/dynamic-prompt/update",
    response_model=PromptUpdateResponse,
    dependencies=[Depends(verify_api_key)],
    summary="Update the dynamic prompt agent",
    description="""
    Update the dynamic prompt agent's system prompt at runtime.
    Provide a new prompt in the request payload and receive the updated prompt in response.
    """
)
async def dynamic_prompt_update(request: PromptUpdateRequest):
    updated_prompt = update_system_prompt(request.new_prompt)
    return PromptUpdateResponse(prompt=updated_prompt)

@router.post(
    "/dynamic-prompt/execute",
    response_model=DynamicPromptExecuteResponse,
    dependencies=[Depends(verify_api_key)],
    summary="Execute the dynamic prompt agent",
    description="""
    Execute the dynamic prompt agent using the current system prompt and provided input.
    The agent's generated response is returned in the response payload.
    This endpoint supports both HTTP calls and internal invocations.
    """
)
async def dynamic_prompt_execute(request: DynamicPromptExecuteRequest):
    result = execute_dynamic_prompt_agent({"input": request.input})
    return DynamicPromptExecuteResponse(response=result)
